# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m6hoPtFL3UYy9QfNgmVFyGdjorym6dPv
"""

import matplotlib.pyplot as pl
pl.bar([1,2,3,4,5,6],[2,3,4,5,6,7],label="Male", color='g', width=0.5)
pl.bar([10,20,30,40,50,60],[20,30,40,50,60,70])
pl.xlabel("Test1")
pl.ylabel("Test2")
pl.show()

#Create a Numpy
import numpy as np
a=np.array([1,10,20,30,40])
a1=np.repeat(a,3)
print(a1)
a2=np.tile(a,3)
print(a2)
b=np.array([[1,2,3,4,5],[20,30,40,50,60]])
#print even numbers from 2 to 100
c=np.arange(2,100,2)
d=np.linspace(2,20,3)
print(a)
print(b[0,2])
print(c)
print(d)
#create a array of random numbers between 0 and 2
m=np.random.rand(10)
x=np.random.rand(3,4)
print(m)
print(x)
#create an array of constant values
z=np.full((2,3),5)
print(z)
#Identity
x1=np.eye(3)
print(x1)
#create a 4x4 array with random numbers
p=np.random.rand(4,4)
print(p)

print(np.sum(p,axis=0)) # print sum along the column
print(np.sum(p,axis=1)) #print sum along the row

print(np.mean(b))
print(np.median(b))
print(np.std(b))

m=np.random.rand(5,5)
print(np.sort(m))
x=np.array([1,3,5,7,9])
y=np.append(x,[51,52,53])
print(y)

from matplotlib import pyplot as pl
pl.bar([1,1.25,1.5,2,2.5],[10,20,30,40,50],color='r',width=0.5,label="Class1")
pl.legend()
pl.xlabel("Test1")
pl.ylabel("Test2")
pl.show()

from matplotlib import pyplot as pl
a=[1,2,3,4,5,6,7]
b=[20,30,40,50,60,70]
pl.hist([a,b])
#pl.legend()
pl.xlabel("Test1")
pl.ylabel("Test2")
pl.show()

from matplotlib import pyplot as pl
x=[1,2,3,4,5]
y=[1.75,1.24,2.3,2.9,3.4]
x1=[10,20,30,40,50]
y1=[10.12,20.22,32.33,44.43,54.43]
pl.scatter(x,y, color='r', label="delhi")
pl.scatter(x1,y1, color='c', label="Karnataka")
pl.legend()
pl.xlabel("Test1")
pl.ylabel("Test2")
pl.show()

from matplotlib import pyplot as pl
parts=[10,20,30,40]
individuals=["R","H","A","B"]
pl.pie(parts, labels=individuals, startangle=90, shadow=True, explode=(0,0.1,0,0)
pl.show()

