# -*- coding: utf-8 -*-
"""25feb(self).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LSaXnmomcm2thHOguGZYwQQZhTWDmA1I
"""

import pandas as pd
x=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/expense_data.csv")

#number of rows in the data frame
len(x)

# select a column
x.INR

# select rows 5 to 10
x[5:10]

# check if any lines are duplicated
x.duplicated

# remove duplicates based on all columns
x.drop_duplicates()

# check data type
x["INR"].dtype

x["INR"].sum()

x["INR"].mean()

