# -*- coding: utf-8 -*-
"""25feb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smQ-_yWBvAbYoxFIk5NaoKSYkeG4G8SM
"""

import pandas as pd
x=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/police.csv")

x.shape #gives information about the shape of data frame

x.head() #top 5 rows

x.tail() #bottom 5 rows

x.isnull()#all columns that are null

x.isnull().sum() #number of all columns that are null

x.mean(axis=0) #mean of all columns

x.info() #information about data variables

#choose n number of random samples from dataframe
x.sample(5)

#get the standard mathematical functions
x.describe()

#find the distinct values from data frame
x.nunique()

#how to find missing values in a dataset
x.isna().any()

#how to get column names
x.columns

#get smallest and largest value in a data frame
x.nsmallest(10,'driver_age')
x.nlargest(10,'driver_age')

